spring:
  cloud:
    gateway:
      routes: 
        - id: USERS-SERVICE
          uri: http://185.125.202.202:9092
          predicates:
            - Path=/users/**
        - id: AUTH-SERVICE
          uri: http://185.125.202.202:9001
          predicates:
            - Path=/auth/**
            

