spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            

