spring:
  cloud:
    gateway:
      routes: 
        - id: USERS-SERVICE
          uri: http://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: AUTH-SERVICE
          uri: http://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            

