spring:
  cloud:
    gateway:
      routes: 
        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
            
    loadbalancer:
        ribbon:
          enabled: true
          eureka:
            enabled: false
          servers:
            - url: http://185.125.202.202:9092
            - url: http://185.125.202.202:9091
