spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
        - id: USERS-SERVICE
          uri: http://localhost:9092
          predicates:
            - Path=/users/**
        - id: AUTH-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/auth/**
            

