spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
        - id: USERS-SERVICE
          uri: http://185.125.202.202:9002
          predicates:
            - Path=/users/**
        - id: AUTH-SERVICE
          uri: http://185.125.202.202:9001
          predicates:
            - Path=/auth/**
            

